### PR TITLE
Add docs folder using mkdocs

### PR DESCRIPTION
**Pull request by askeluv**
Currently the README.md file covers a lot of ground, which makes it somewhat difficult to process for newcomers.

This PR moves documentation into a docs folder, with an accompanying mkdocs.yml file. This will let us publish our docs on readthedocs.io in a more structured way.

### CODE REVIEW

**Comment by askeluv** [comment]
Still need to update some of the relative links. Also, the repo link won't work before we deploy.

**Comment by medvedev1088** [comment]
Created build in readthedocs for this branch for review https://ethereum-etl.readthedocs.io/en/feature-add-docs/

**Comment by medvedev1088** [comment]
@askeluv I made a few changes. Added useful links to README, moved Tests and Docker to README as they depend on repo contents and a few minor changes. If everything looks ok on yours side I'm going to merge it.

**Review by medvedev1088 — APPROVED** [review]

**Comment by askeluv** [comment]
Looks great! Let's ship it.

**Pull request merged**
