### PR TITLE
Added exporter for kafka

### PR DESCRIPTION
**Pull request by ayush3298**
TL;DR
Adds support for Kafka
<hr>  

### Synopsis  
This extension allows for streaming files from the ETL app directly to Kafka:

### Usage
Need to pass "kafka" in output url and pass another url that is connection url for kafka

### CODE REVIEW

**Comment by medvedev1088** [comment]
Thanks for the PR. Why closed?

**Comment by beyondblog** [comment]
This is a very good PR, I look forward to it reopening

**Comment by ayush3298** [comment]
Reopening Thanks

**Comment by ayush3298** [comment]
Opened it here [https://github.com/blockchain-etl/ethereum-etl/pull/291](url)

**Pull request closed without merging**
