### PR TITLE
Add support for extracting Origin Protocol data

### LINKED ISSUE #215: Add support for extracting Origin Protocol's data
Per @allenday's recommendation, I'm filing this issue to discuss the possibility of adding capabilities for extracting data from [Origin Protocol](https://www.originprotocol.com/).

For context, Origin Protocol implemented an [open source platform](https://github.com/OriginProtocol/origin) on top of Ethereum and [IPFS](https://ipfs.io/) for building decentralized marketplaces. [shoporigin.com](https://shoporigin.com/) and [brave.store.com](https://store.brave.com/#/) are examples of such marketplaces. The foundational component of the platform is the [marketplace smart contract](https://etherscan.io/address/0x698ff47b84837d3971118a369c570172ee7e54c2#code) which allows sellers and buyers to transact. Non-transactional data (ex: listing description, images, etc...) is stored on IPFS and the marketplace contract stores "pointers" (more specifically IPFS hashes) to that data. Additionally, the marketplace contract emits [events](https://github.com/OriginProtocol/origin/blob/master/packages/contracts/contracts/marketplace/V01_Marketplace.sol#L50) which can be used as triggers by external systems (for example for indexing data).

We implemented a prototype (see draft PR #214 ) that demonstrates how the data could get extracted. It listens for events issued by the marketplace contract, loads the relevant data from IPFS and currently outputs data from the 2 types of marketplaces currently supported by the platform:
 - peer-to-peer listings (those created on shoporigin.com for example)
 - inventory of products from "decentralized shops" (store.brave.com for example).

Samples of the extracted data can be found in the following big query public tables:
 - origin-214503.dshop.products (and also [here](https://storage.googleapis.com/origin_bigquery_prototype/products.json) as csv in cloud storage)
 - origin-214503.marketplace.listings (and also [here](https://storage.googleapis.com/origin_bigquery_prototype/marketplace.json) as a csv in cloud storage)

In addition to providing a tool for the open source community to extract data from Origin Protocol's marketplace contract, we also think there is benefit in including in the ethereum-etl project a concrete example of how to extract data that is stored both on chain and on IPFS. Given its decentralized and immutable nature, we expect IPFS to become a popular option for blockchain developers for storing side metadata (storing data on chain is quite expensive and is in many case not an economically viable option for data larger than a few dozen bytes).

Please let me know your thoughts and any questions... Thanks in advance ! :)

### PR DESCRIPTION
**Pull request by franckc**
This implements a prototype that extracts data generated by Origin Protocol's open source platform for building decentralized marketplaces on Ethereum and IPFS.

Fixes https://github.com/blockchain-etl/ethereum-etl/issues/215

### CODE REVIEW

**Comment by askeluv** [comment]
Hey @franckc, maybe you've already considered this, but have you checked out this repo: https://github.com/blockchain-etl/ethereum-etl-airflow ? It might make it easier to extract at least parts of the data. A bit more context here: https://towardsdatascience.com/how-to-get-any-ethereum-smart-contract-into-bigquery-in-8-mins-bab5db1fdeee

**Comment by franckc** [comment]
@askeluv Thanks for the links :) I had looked at ethereum-etl-airflow but had missed the tasks that allow to parse events from specific smart contracts and to load those in dedicated tables under the blockchain-etl BigQuery dataset (by the way, kudos on those tools, they are pretty cool and make it really easy to add a table definition).

I think it would make sense for me to add the Orign Protocol marketplace contract to ethereum-etl-airflow's [table definitions](https://github.com/blockchain-etl/ethereum-etl-airflow/tree/master/dags/resources/stages/parse/table_definitions). This in itself is a dataset that could be useful to people for querying the events generated by our contract. And using your tool makes it really simple to add those table definitions!


Separately, regarding the pipeline for populating Origin Protocol's "listings" and "products" BigQuery tables which are derived off both events data and IPFS data, I could see 2 options:
   1. Add an ethereum-etl job that only exports the IPFS data. The event data as a whole is already extracted via the export_receipt_and_logs ethereum-etl job. Add ethereum-etl-airflow tasks to run the IPFS export job  and to combine the relevant event data with the IPFS data and load it into the "listings" and "products" BigQuery tables.
   1. Add an ethereum-etl job to export the combined event and IPFS data (this is what this draft PR does). Add ethereum-etl-airflow tasks to run the export and to load the data into the "listings" and "products" BigQuery tables.

I think option 1. could actually make things a bit more complicated compared to option 2. Here is my reasoning:
 - Indexing the whole IPFS corpus is not an option since a) it is huge b) the corpus is composed of any type of content and most of it is irrelevant since it is not associated in any ways with blockchain data c) there is no index or link between content which makes it impossible to crawl the corpus. 
 - Therefore for option 1, the ethereum-etl IPFS data export job would need to know the specific list of IPFS hashes (e.g. IPFS "keys") that are relevant. Given that the only places to get those hashes are blockchain events, the job would need to query event logs, which is what option 2 does...
- In addition, option 1. would also require to write an ethereum-etl-airflow job to combine the event and IPFS data.

So overall I'm leaning towards option 2.

Please let me know any feedback... thanks for your help!

**Comment by askeluv** [comment]
Right, I think your reasoning makes sense. It's definitely a different scenario since it involves IPFS data. I just brought up the `ethereum-etl-airflow` repo in case it would make your life easier :)

**Comment by allenday** [comment]
@franckc PTAL at https://github.com/blockchain-etl/ethereum-etl-airflow/issues/50

Does this design support your IPFS extraction use case? If not, would you be willing to help us to make it more generic?

**Comment by franckc** [comment]
@allenday I added my naive thoughts to blockchain-etl/ethereum-etl-airflow#50 - Overall I think it would work well for Origin Protocol's use case.

Now, if I may ask, what horizon would we be looking at for the streaming solution to get rolled out and ready to use?

I'd love to have a (even if it's interim) solution rolled out for Origin Protocol soon. So I'm thinking that unless there is any objection I should still go ahead and finish this PR to integrate with ethereum-etl, then once the streaming solution becomes available I can move to that new architecture?

Thanks for the guidance... :)

**Comment by franckc** [comment]
@medvedev1088 @allenday Just confirming with you that you are ok with the plan I outlined above. In essence:
1. Clean up this PR and submit it for review with the goal of merging it into ethereum-etl. This is the short-term solution.
2. Longer term solution is to use the new streaming infrastructure described in blockchain-etl/ethereum-etl-airflow#50 once it becomes available. And I'd be happy to be a beta tester for it obviously.

Thank you!

**Comment by medvedev1088** [comment]
@franckc the plan you outlined above looks good to me!

**Comment by franckc** [comment]
Sounds good. Thank you. I'm going ahead with this plan then :)

**Comment by franckc** [comment]
@medvedev1088 I did some clean up and added some unit tests so this is now ready for review... Thanks for your help!

**Comment by medvedev1088** [comment]
Thank you! I will try to review and merge it this week.

**Pull request merged**
