### PR TITLE
adds support for non-mainnet in etl stream

### PR DESCRIPTION
**Pull request by numonedad**
relates #178

DEMO on ronin network, an eth sidechain. Notice that latest block can now be read, thanks to middleware injection.
```
2021-08-12 19:24:34,321 - ProgressLogger [INFO] - Started work. Items to process: 1.
2021-08-12 19:24:34,375 - ProgressLogger [INFO] - 1 items processed. Progress is 100%.
2021-08-12 19:24:34,375 - ProgressLogger [INFO] - Finished work. Total items processed: 1. Took 0:00:00.054600.
2021-08-12 19:24:34,376 - ProgressLogger [INFO] - Started work.
2021-08-12 19:24:34,376 - ProgressLogger [INFO] - Finished work. Total items processed: 0. Took 0:00:00.000169.
2021-08-12 19:24:34,376 - ProgressLogger [INFO] - Started work.
2021-08-12 19:24:34,376 - ProgressLogger [INFO] - Finished work. Total items processed: 0. Took 0:00:00.000143.
```

### CODE REVIEW

**Comment by happy888liu** [comment]
why i can't access ronin blockchain by web3.py ,but i can access ronin by web3.js 
"'https://api.roninchain.com/rpc'"

**Comment by drewwells** [comment]
> why i can't access ronin blockchain by web3.py ,but i can access ronin by web3.js
> "'https://api.roninchain.com/rpc'"

skymavis disabled all non essential endpoints. You now have to run your own rpc

**Comment by happy888liu** [comment]
i don't know to build my own rpc about Ronin chain 😭  have any tools?

**Comment by happy888liu** [comment]
> > why i can't access ronin blockchain by web3.py ,but i can access ronin by web3.js
> > "'https://api.roninchain.com/rpc'"
> 
> skymavis disabled all non essential endpoints. You now have to run your own rpc

i see geth document,but how i syncing ronin chain ,or geth will syncing eth sidechain  at same time? 😢

**Comment by drewwells** [comment]
it’s a geth fork, you can not sync it with geth. You need their private fork of geth to sync this chain.

**Comment by happy888liu** [comment]
> it’s a geth fork, you can not sync it with geth. You need their private fork of geth to sync this chain.

i don't find anything in google ,it seem that i can't sync ronin chain 😢

**Comment by NickKelly1** [comment]
Looking forward to this :+1:

**Comment by NickKelly1** [comment]
Any updates on this?

Still running into this

```bash
# chain doesn't seem to make a difference
ethereumetl get_block_range_for_date --provider-uri=http://127.0.0.1:8545 --date=2021-12-12 --chain=goerli

# ...
#   File "/home/nickk/.local/lib/python3.8/site-packages/web3/middleware/validation.py", line 49, in
# check_extradata_length
#     raise ValidationError(web3.exceptions.ValidationError: The field extraData is 97 bytes, but
# should be 32. It is quite likely that you are connected to a POA chain. Refer
# http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more
# details. The full extraData is:
# HexBytes('0x506172697479205465636820417574686f7269747900000000000000000000002
# bbf886181970654ed46e3fae0ded41ee53fec702c47431988a7ae80e6576f3552684f069af80ba1
# 1d36327aaf846d470526e4a1c461601b2fd4ebdcdc2b734a01')
```

**Comment by medvedev1088** [comment]
Please try version 1.10.0 and let me know if it works @NickKelly1

**Comment by NickKelly1** [comment]
> Please try version 1.10.0 and let me know if it works @NickKelly1

@medvedev1088 It works, thanks!

```bash
get_block_range_for_date --provider-uri=http://127.0.0.1:8545 --date=2021-12-12 --chain=goerli
# 6006077,6011836
get_block_range_for_date --provider-uri=http://127.0.0.1:8545 --date=2021-12-12
# 6006077,6011836
```

**Pull request merged**
