### PR TITLE
Add block_timestamp attribute to exported PubSub message

### PR DESCRIPTION
**Pull request by obsh**
Timestamp attribute on PubSub messages can simplify downstream processing.

For example, when using Apache Beam -  PubsubIO can assign timestamp using message attribute:
https://beam.apache.org/releases/javadoc/2.19.0/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.Read.html#withTimestampAttribute-java.lang.String-

Conversion to string added, because otherwise the error appears:
"All attributes being published to Pub/Sub must be sent as text strings"

### CODE REVIEW

**Comment by medvedev1088** [comment]
Thanks for the PR @obsh! From the documentation it seems that the timestamp attribute has to be either in milliseconds since epoch or in RFC 3339, while our `timestamp` and `block_timestamp` fields are in seconds since epoch. If that's the case, one way to handle it is to add the `item_timestamp` field with RFC 3339 format to the exported dicts, in a similar way item_ids are added here https://github.com/blockchain-etl/ethereum-etl/blob/develop/ethereumetl/streaming/eth_streamer_adapter.py#L96. Then in pubsub_exporter pass message_attributes=('item_id', 'item_timestamp').

Apart from that I had a plan to migrate to using ISO8601 or RFC3339 across all blockchain-etl tools as it seems to be more interoperable than unix timestamps. But that's a different task.

**Comment by obsh** [comment]
@medvedev1088 thanks for pointing out seconds/milliseconds timestamp type mismatch. I really haven't noticed it.
As you suggested I've implemented now `item_timestamp` attribute in RFC3339 format.

**Review by medvedev1088 — APPROVED** [review]
Great job! I'll try to deploy it this week.

**Comment by medvedev1088** [comment]
Deployed to prod. Tested by creating a subscription and pulling a message using steps in this article https://medium.com/google-cloud/live-ethereum-and-bitcoin-data-in-google-bigquery-and-pub-sub-765b71cd57b5.

**Comment by obsh** [comment]
Thank you!

**Pull request merged**
