### PR TITLE
Implement CLI with Click package

### PR DESCRIPTION
**Pull request by elim0322**
(1) Click package is implemented to replace argparse
(2) `README.md` is updated. It was hard to read subsections under "Command Reference" so bumped up the section level.
(3) Click is added to `requirements.txt`

### CODE REVIEW

**Comment by elim0322** [comment]
Yep sounds great! I'll make those changes and let you know when it's ready for review :)

**Comment by elim0322** [comment]
Yep sounds great! I'll make those changes and let you know when it's ready for review :)

**Comment by elim0322** [comment]
Yep sounds great! I'll make those changes and let you know when it's ready for review :)

**Comment by elim0322** [comment]
Yep sounds great! I'll make those changes and let you know when it's ready for review :)

**Comment by elim0322** [comment]
@medvedev1088 Yep sounds great! I'll make those changes and let you know when it's ready for review :)

**Comment by elim0322** [comment]
@medvedev1088 Yep sounds great! I'll make those changes and let you know when it's ready for review :)

**Comment by elim0322** [comment]
@medvedev1088 Sounds great! I’ll make those changes and let you know once it’s ready for review :)

**Comment by medvedev1088** [comment]
@elim0322 great job!

**Pull request merged**
