### PR TITLE
Fix datatype

### PR DESCRIPTION
**Pull request by sfsf9797**
image
image
Seem like `l1FeeScalar`  is not a Hex, this pr addresses the datatype mismatch issue.

### CODE REVIEW

**Comment by jensenity** [comment]
Getting the error too. Need to update this @allenday 
```
Not a hex string 0.684
Not a hex string 0.684
Not a hex string 0.684
Not a hex string 0.684
Not a hex string 0.684
Not a hex string 0.684
Not a hex string 0.684
Not a hex string 0.684
Not a hex string 0.684
```

**Comment by medvedev1088** [comment]
@MSilb7 I'd appreciate your review

**Comment by MSilb7** [comment]
> @MSilb7 I'd appreciate your review

ah yeah this is great!

**Comment by medvedev1088** [comment]
https://github.com/blockchain-etl/ethereum-etl/releases/tag/v2.3.1
@sfsf9797 @jensenity, could you please test it? Thank you!

**Comment by sfsf9797** [comment]
@medvedev1088 sure! It works fine for me.

**Pull request merged**
