### PR TITLE
implementation of internal transaction exporter

### LINKED ISSUE #53: Add support for internal transactions
Parity provides APIs for retrieving [internal transactions](https://github.com/paritytech/wiki/blob/master/JSONRPC-trace-module.md). [trace_filter](https://github.com/paritytech/wiki/blob/master/JSONRPC-trace-module.md#trace_filter) API allows retrieving traces for a range of blocks. This method is already supported by web3.py [parity module](https://github.com/ethereum/web3.py/blob/master/web3/parity.py).

The scope of this task is to 
1. Design the model (the field names from this PR can be used as a basis: https://github.com/blockchain-etl/ethereum-etl/pull/72).
2. Implement the export job (the job implementation will mostly resemble the flow in [ExportTokenTransfersJob](https://github.com/blockchain-etl/ethereum-etl/blob/master/ethereumetl/jobs/export_token_transfers_job.py).
3. Write unit tests (an example can be found [here](https://github.com/blockchain-etl/ethereum-etl/blob/master/tests/ethereumetl/job/test_export_token_transfers_job.py))
4. Add documentation to README (an example can be found [here](https://github.com/blockchain-etl/ethereum-etl#export_token_transferspy))
(5. Add instructions for how to start parity/geth i.e. what options to use).

=======================

Remarks:
- There will be another task to add the BigQuery schema [here](https://github.com/blockchain-etl/ethereum-etl-airflow/tree/master/dags/resources/stages/raw/schemas)
- Geth also provides support for tracing transactions. There will be another task for implementing internal transactions exporter job for Geth. https://github.com/ethereum/go-ethereum/pull/15516, https://www.linkedin.com/pulse/geth-18-iceberg-michael-hunt-jr-

### PR DESCRIPTION
**Pull request by evgeniuz**
Fixes #53

### CODE REVIEW

**Comment by medvedev1088** [comment]
@evgeniuz great job!

> block_timestamp requires additional call to getBlock for each block, as trace_filter does not return it. Should I remove this field?

Yes let's remove it.

> contract_address should contain "Address of the contract which initiated the transaction", but in the context of internal transaction that is always equals from address, as this is address that initiated transaction. What is the purpose of having separate field?

I think the description of the field is wrong there. It should be "The address of the created contract for 'create' trace type". It should be in the `result.address` field in the returned traces. You can also refer here https://github.com/analyseether/ether_sql/blob/master/ether_sql/models/traces.py#L122.

> call (and it's subtypes) and create transactions are fitting to these fields (with small adjustments: create is missing to and input, but we can use zero address and init respectively as fair substitutes). But suicide transactions are special, they miss lots of fields (i. e. from, to, value, input, gas, gas_used). And have special fields like balance, address (of destroyed contract) and refundAddress. Should I store them in same file anyway or should I make separate output for suicide calls?

Let's keep them in the same file and map the fields the same way as it's done here for simplicity https://github.com/analyseether/ether_sql/blob/master/ether_sql/models/traces.py#L136. I.e 
`address` -> `from_address`, 
`refundAddress` -> `to_address`, 
`balance` -> `value`.

> Should this job only export internal transactions (initiated by contracts) or normal ones as well?

Let's include them all. Let's also not skip traces with type 'reward'. This way it will be less surprising for users as they can simply refer to parity docs to know what's included in the table.

Could you also add these fields:

`transaction_hash` - hash of the transaction
`subtraces` - the number of subtraces

Rename `transaction_type` to `trace_type` (`transaction_type` may be confusingly understood as referring to type of transaction instead of internal transaction) and remove `is_error` field (seems redundant).

I'm also thinking about renaming `internal_transactions` to `traces` for consistency with parity and geth but it doesn't have to be in the scope of this task (I can create a separate task).

Thanks!

**Comment by evgeniuz** [comment]
Renamed `internal_transactions` to `traces`, improved fields as suggested, added tests with fixtures based on mainnet responses. Reward fields are not skipped now, they don't have a lot of fields (even `transaction_hash`, but I've mapped `to_address` to block author (since that's where value goes, this seems to make sense).

**Comment by evgeniuz** [comment]
rebased on top of `develop` branch

**Comment by rraina** [comment]
Nice job @evgeniuz !

**Pull request merged**
