### PR TITLE
Python 3.5/3.7 compatibility and tox integration

### LINKED ISSUE #123: Add support for Python 3.5 and 3.7
The scope of this task is:
- Test that all commands work in Python 3.5 and 3.7. 
- Change the code where necessary (e.g. `f''` string formatting is not supported in Python 3.5)
- Write tox config for Python 3.5, 3.6, 3.7 (example tox usage can be found here https://github.com/ethereum/web3.py)
- Update README with instructions on how to run tox tests.
- Travis CI configuration and testing that it works in Travis CI server.

Notes:
- All dependencies in this project support python 3.5 and 3.7. https://pypi.org/project/click/, https://github.com/ethereum/web3.py

### PR DESCRIPTION
**Pull request by evgeniuz**
Fixes #123

### CODE REVIEW

**Comment by evgeniuz** [comment]
Added tox support, fixed a few incompatibilities:

- only change so far in code (other changes are in tests): `datetime.combine` doesn't accept `tzinfo` parameter in 3.5, but takes it from `time` parameter, changed this to set `tzinfo` to time instead of passing it as parameter;
- dictionaries are unordered by default in 3.5 and ordered in 3.6+, changed `compare_lines_ignore_order` helper to support comparing unordered JSON files;
- tmpdir is path-like object, support for these was added in 3.6+, casted it with `str()` for compatibility with 3.5.

Also, moved dev requirements to `setup.py` and updated docs. Next steps: use `tox` for Travis, use old formatting instead of `f''` strings (these are only found in `export_all` and `export_all_common`, so don't affect tests).

**Comment by evgeniuz** [comment]
Added tox to Travis, replaced f-string with str.format.

**Comment by evgeniuz** [comment]
@medvedev1088 Just pinging, this is ready for review.

**Comment by medvedev1088** [comment]
@evgeniuz would you be interested in working with Airflow and Google Cloud Composer? I need this DAG rewritten to use PythonOperator instead of BashOperator https://github.com/blockchain-etl/ethereum-etl-airflow/blob/master/dags/export_dag.py. I can also give you access to a GCP project for testing. If you are interested I can create a task and request a bounty for it.

**Comment by evgeniuz** [comment]
@medvedev1088, sure, I'm up for it.

**Comment by medvedev1088** [comment]
I created this issue and requested the bounty https://github.com/blockchain-etl/ethereum-etl-airflow/issues/2. Waiting for approval.

**Pull request merged**
