### PR TITLE
Add block timestamp to transactions.csv

### PR DESCRIPTION
**Pull request by t2y**
Currently, schema of `transactions.csv` does not have block timestamp. I think that there are several use cases with block timestamp when a `transactions.csv` is handled as time series data. So, I propose adding block timestamp into it.

However, this change breaks the compatibility and increase `transactions.csv` data size and exporting run time. I'm not sure my proposal is general needs or not.

I can add a cli option to switch whether `transactions.csv` has block timestamp or not. What do you think?

### CODE REVIEW

**Comment by tokusyu** [comment]
I can understand the use case analyzing transactions with timestamp.

In my case, I use Apache Spark to get a timestamp from corresponding block.
In spark, I perform additional tasks e.g. converting timestamp from UTC to JST, gzippng data , adding status before Byzantium HF and integrating transactions and receipts.

I suppose others have their own tasks.
So it will be controversal topic which column should be included on transactions.

**Comment by medvedev1088** [comment]
While I agree that the timestamp can be added in the ETL pipeline, it also looks like a relatively simple change that can add significant value to some people. The biggest downside is broken compatibility. 

One way to approach it would be to add this column as the last column of the csv file. @tokusyu will your ETL pipeline break if there is a new column added to transactions.csv?

Another approach is to bump the version to 2.0.0. 

Yet another approach is to use JSON instead of CSV which is resistant to schema changes, but it has its own downsides.

**Comment by tokusyu** [comment]
Adding it at the last column may not break my pipeline. Just ignoring it. 
Reordering columns will break my system.
Thanks.

**Comment by t2y** [comment]
@medvedev1088 @tokusyu Thank you for your review! I changed block_timestamp column position to last column.

> Yet another approach is to use JSON instead of CSV which is resistant to schema changes, but it has its own downsides.

I agree with providing JSON format and I think that providing `--format` option to be able to select csv/json is better.

**Pull request merged**
